/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.formthi;

import JComponent.ExamRdoButton;
import JComponent.anwserside;
import Model.DapAnModel;
import Model.Thimodel;
import SerVic.CauHoiServic;
import SerVic.ObjectIsCauhoi;
import SerVic.ThiServic;
import Util.MessageConfig;
import Util.cookieNguoiDung;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Enumeration;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import view.mainform;

/**
 *
 * @author Admin
 */
public class FormthiPnTop extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    int dung = 0;
    int sai = 0;
    int khongtraloi = 0;
    public static JLabel lblindex;
    int thoigian;
    FormThi parentForm;
    String madethi;
    private ThiServic thiServic;

    public FormthiPnTop(String madethi, ButtonGroup ques, ButtonGroup anw, Map<Integer, ObjectIsCauhoi> map, FormThi form, String tenmonhoc, String tendethi, int thoigianparam) {
        initComponents();
        lblindex = new JLabel("1/50");
        lbltendethi.setText(tendethi);
        lblmohoc.setText(tenmonhoc);
        lblindex.setFont(new Font("Tahoma", Font.BOLD, 18));
        lblindex.setForeground(Color.gray);
        this.madethi = madethi;
        thiServic = new ThiServic();
        pnindex.add(lblindex);
        pnindex.setLayout(new BoxLayout(pnindex, BoxLayout.Y_AXIS));
        btnhoanthanh.setEnabled(false);
        btntrangchu.setEnabled(false);
        parentForm = form;
        this.thoigian = thoigianparam;
        new Thread(new Runnable() {
            int giay = 60;

            @Override
            public void run() {
                while (thoigian >= 0) {
                    thoigian--;
                    if (FormThi.STATEFINISH) {
                        break;
                    }
                    if (thoigian >= 0) {
                        while (giay >= 0) {
                            if (FormThi.STATEFINISH) {
                                break;
                            }
                            try {
                                lbltime.setText(thoigian + ":" + giay);
                                giay--;
                                System.out.println(giay);
                                Thread.sleep(1000);
                            } catch (InterruptedException ex) {
                                Logger.getLogger(FormthiPnTop.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        giay = 60;
                    }
                }
                if (!chkcheck.isSelected()) {
                    chkcheck.setSelected(true);
                }
                if (thoigian <= 0) {
                    FormThi.STATEFINISH = true;
                    finish();
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnhoanthanh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblmohoc = new javax.swing.JLabel();
        lbltendethi = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        chkcheck = new javax.swing.JCheckBox();
        lbldung = new javax.swing.JLabel();
        lblsai = new javax.swing.JLabel();
        lblkhongtraloi = new javax.swing.JLabel();
        lbltongdiem = new javax.swing.JLabel();
        pnindex = new javax.swing.JPanel();
        btntrangchu = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lbltime.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        lbltime.setForeground(new java.awt.Color(153, 153, 153));
        lbltime.setText("49:59");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Thời Gian Còn");

        btnhoanthanh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnhoanthanh.setText("Nộp Bài");
        btnhoanthanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhoanthanhActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Môn Thi");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Đề Thi");

        lblmohoc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblmohoc.setForeground(new java.awt.Color(153, 153, 153));
        lblmohoc.setText("Toán");

        lbltendethi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltendethi.setForeground(new java.awt.Color(153, 153, 153));
        lbltendethi.setText("Đề Thi Thử THPT Quốc Gia Năm 2019");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_64px_1.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        chkcheck.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        chkcheck.setText("I want to finish");
        chkcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkcheckActionPerformed(evt);
            }
        });

        lbldung.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbldung.setForeground(new java.awt.Color(153, 153, 153));

        lblsai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblsai.setForeground(new java.awt.Color(153, 153, 153));

        lblkhongtraloi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblkhongtraloi.setForeground(new java.awt.Color(153, 153, 153));

        lbltongdiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltongdiem.setForeground(new java.awt.Color(153, 153, 153));

        pnindex.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnindexLayout = new javax.swing.GroupLayout(pnindex);
        pnindex.setLayout(pnindexLayout);
        pnindexLayout.setHorizontalGroup(
            pnindexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
        pnindexLayout.setVerticalGroup(
            pnindexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        btntrangchu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btntrangchu.setText("Trang Chủ");
        btntrangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntrangchuMouseClicked(evt);
            }
        });
        btntrangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrangchuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmohoc)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltime)
                        .addGap(74, 74, 74)
                        .addComponent(pnindex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(lblkhongtraloi, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(lbltongdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltendethi)
                        .addGap(125, 125, 125)
                        .addComponent(lbldung, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblsai, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 508, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btntrangchu)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chkcheck)
                        .addGap(41, 41, 41)
                        .addComponent(btnhoanthanh, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblmohoc))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbltendethi)
                    .addComponent(lbldung, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltongdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblkhongtraloi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pnindex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltime)
                            .addComponent(jLabel2))))
                .addGap(0, 60, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(20, 20, 20)
                .addComponent(btntrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhoanthanh, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkcheck))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkcheckActionPerformed
        // TODO add your handling code here:
        btnhoanthanh.setEnabled(!btnhoanthanh.isEnabled());
    }//GEN-LAST:event_chkcheckActionPerformed

    private void btnhoanthanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhoanthanhActionPerformed
        // TODO add your handling code here:
        FormThi.STATEFINISH = true;
        finish();
    }//GEN-LAST:event_btnhoanthanhActionPerformed

    private void btntrangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrangchuActionPerformed
        // TODO add your handling code here:
        parentForm.dispose();
        try {
            FormThi.STATEFINISH = false;
            new mainform().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormthiPnTop.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormthiPnTop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btntrangchuActionPerformed

    private void btntrangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntrangchuMouseClicked
        // TODO add your handling code here:
        if (!btntrangchu.isEnabled()) {
            MessageConfig.messageText("Bạn Phải Nộp Bài Trước", this);
        }
    }//GEN-LAST:event_btntrangchuMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int choose = MessageConfig.messagechooseYesNo("Nếu Thoát Ra Kết Quả Sẽ Không Được Ghi Nhận", "Thông Báo", this);
        if (choose == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void insertThiThu() {
        Thimodel thi = new Thimodel();
        thi.setTaikhoan(cookieNguoiDung.NGUOIDUNG.getTaikhoan());
        thi.setKhongtraloi(khongtraloi);
        thi.setSocaudung(dung);
        thi.setSocausai(sai);
        thi.setMadethi(madethi);
        thiServic.insert(thi);
    }

    public void finish() {
        enablebuttonAnwser();
        for (Enumeration<AbstractButton> buttons = ExamRdoButton.btgroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            ObjectIsCauhoi obj = CauHoiServic.map.get(Integer.parseInt(button.getActionCommand()));
            if (obj != null) {
                if (obj.getDapandung().equals(obj.getNguoidungchon())) {
                    button.setForeground(Color.GREEN);
                    dung++;
                } else {
                    button.setForeground(Color.red);
                    sai++;
                }
            } else {
                button.setForeground(Color.gray);
                khongtraloi++;
            }
        }
        insertThiThu();
        setlbl();
        btnhoanthanh.setEnabled(false);
        chkcheck.setEnabled(false);
        btntrangchu.setEnabled(true);
    }

    public void setlbl() {
        lbldung.setText("Số Câu Đúng : " + dung);
        lblsai.setText("Số Câu Sai : " + sai);
        lblkhongtraloi.setText("Không Trả Lời : " + khongtraloi);
        DecimalFormat twoDForm = new DecimalFormat("#.##");
        lbltongdiem.setText("Tổng Điểm : " + twoDForm.format(dung * (10.0 / FormThi.listCauHoi.size())));
        dung = 0;
        sai = 0;
        khongtraloi = 0;
    }

    public void enablebuttonAnwser() {
        ObjectIsCauhoi obj = CauHoiServic.map.get(FormThi.STT);
        if (obj != null) {
            for (Enumeration<AbstractButton> buttons = anwserside.group.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();
                button.setForeground(Color.black);
                if (button.getActionCommand().equals(obj.getNguoidungchon())) {
                    button.setForeground(Color.red);
                }
                if (button.getActionCommand().equals(obj.getDapandung())) {
                    button.setForeground(Color.GREEN);
                    button.setSelected(true);
                }
                button.setEnabled(false);
            }
        } else {
            for (Enumeration<AbstractButton> buttons = anwserside.group.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();
                button.setForeground(Color.black);
                String dapandung = null;
                for (DapAnModel da : FormThi.listCauHoi.get(FormThi.STT).getListDapAn()) {
                    if (da.getTrangthai().equals("TRUE")) {
                        dapandung = da.getLoaidapan();
                    }
                }
                if (button.getActionCommand().equals(dapandung)) {
                    button.setForeground(Color.pink);
                    button.setSelected(true);
                }
                button.setEnabled(false);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhoanthanh;
    private javax.swing.JButton btntrangchu;
    private javax.swing.JCheckBox chkcheck;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbldung;
    private javax.swing.JLabel lblkhongtraloi;
    private javax.swing.JLabel lblmohoc;
    private javax.swing.JLabel lblsai;
    private javax.swing.JLabel lbltendethi;
    private javax.swing.JLabel lbltime;
    private javax.swing.JLabel lbltongdiem;
    private javax.swing.JPanel pnindex;
    // End of variables declaration//GEN-END:variables
}
