/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.formthi;

import FormatDom.CauHoiDom;
import FxForm.FxWebview;
import JComponent.ExamRdoButton;
import JComponent.anwserside;
import Model.CauHoiModel;
import SerVic.CauHoiServic;
import Util.JDBC;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Admin
 */
public class FormThi extends javax.swing.JFrame {

    public static int STT = 0;
    public CauHoiServic cauHoiServic;
    public static List<CauHoiModel> listCauHoi;
    private FxWebview fw;
    public static boolean STATEFINISH = false;
    String madethi;

    /**
     * Creates new form NewJFrame
     */
    public FormThi(String madethi,String tenmonhoc,String tendethi,int thoigian) {
        initComponents();
        this.madethi = madethi;
        cauHoiServic = new CauHoiServic();
        listCauHoi = cauHoiServic.select(madethi);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        createFWview();
        createForm(tenmonhoc,tendethi,thoigian);
    }

    void createFWview() {
        JPanel pncenter = new JPanel();
        pncenter.setBackground(Color.white);
        add(pncenter, BorderLayout.CENTER);
        fw = new FxWebview(pncenter, CauHoiDom.formatterCauHoiDom(listCauHoi.get(0)), 1150, 750);
        fw.setzoom(1.6);
    }

    void createForm(String tenmonhoc,String tendethi,int thoigian) {

        anwserside pnside = new anwserside(cauHoiServic.map, listCauHoi);
        pnside.setPreferredSize(new Dimension(200, HEIGHT));
        add(pnside, BorderLayout.WEST);
        // tham số buttongroup của anwserside giúp có thể thay đổi selected mỗi khi chuyển câu hỏi
        ExamRdoButton pnsideright = new ExamRdoButton(cauHoiServic.map, listCauHoi, listCauHoi.size(), fw);
        // set btngroup của question cho anwserside để thực hiên đổi màu mỗi khi chọn đáp án
        JScrollPane scrollPane = new JScrollPane(pnsideright);
        scrollPane.setPreferredSize(new Dimension(250, HEIGHT));
        add(scrollPane, BorderLayout.EAST);
        FormthiPnTop pntop = new FormthiPnTop(madethi,pnsideright.getBtgroup(),pnside.getGroup(),cauHoiServic.map,this,tenmonhoc,tendethi,thoigian);
        add(pntop, BorderLayout.NORTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FormThi("DT_01").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
