/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import servic.AccountServic;
import util.JDBC;
import util.MessageConfig;
import util.RegexPattern;

/**
 *
 * @author Admin
 */
public class FormLogin extends javax.swing.JDialog {

    private AccountServic accountServic;
    CardLayout card = null;

    /**
     * Creates new form FormLogin
     */
    public FormLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            JDBC.con = JDBC.getconnect();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        card = (CardLayout) pncard.getLayout();
        accountServic = new AccountServic();
    }

    void login() {
        String matkhau = txtpasslogin.getText();
        if (txttaikkhoanlogin.getText().equals("")) {
            MessageConfig.messageText("không đươc để trống tài khoản", rootPane);
            return;
        }
        if (!RegexPattern.checkgmail(txttaikkhoanlogin.getText())) {
            MessageConfig.messageText("tài khoản không đúng định dạng", rootPane);
            return;
        }
        if (matkhau.equals("")) {
            MessageConfig.messageText("không đươc để trống mật khẩu", rootPane);
            return;
        }
        accountServic.loginadmin(txttaikkhoanlogin.getText(), rootPane, matkhau);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pncard = new javax.swing.JPanel();
        pnlogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttaikkhoanlogin = new javax.swing.JTextField();
        btndangnhap = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        txtpasslogin = new javax.swing.JPasswordField();
        lblquenmatkhau = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnquenmk = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txttaikhoanquenmk = new javax.swing.JTextField();
        lbldangnhap = new javax.swing.JLabel();
        btnguimaxacnhan = new javax.swing.JButton();
        btnthoatquenmk = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pnmaxacnhan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btndoimatkhau = new javax.swing.JButton();
        btnguilaima = new javax.swing.JButton();
        btnthoatxacnhan = new javax.swing.JButton();
        lblgmail = new javax.swing.JLabel();
        txtmaxacnhan = new javax.swing.JTextField();
        txtmatkhaumoi = new javax.swing.JPasswordField();
        txtxacnhanmatkhau = new javax.swing.JPasswordField();
        lbltimeout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pncard.setLayout(new java.awt.CardLayout());

        pnlogin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Tài Khoản");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Mật Khẩu");

        txttaikkhoanlogin.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btndangnhap.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btndangnhap.setText("Đăng Nhập");
        btndangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangnhapActionPerformed(evt);
            }
        });

        btnthoat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        txtpasslogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblquenmatkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblquenmatkhau.setText("Quên Mật Khẩu?");
        lblquenmatkhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblquenmatkhauMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Đăng Nhập");

        javax.swing.GroupLayout pnloginLayout = new javax.swing.GroupLayout(pnlogin);
        pnlogin.setLayout(pnloginLayout);
        pnloginLayout.setHorizontalGroup(
            pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnloginLayout.createSequentialGroup()
                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnloginLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnloginLayout.createSequentialGroup()
                                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnloginLayout.createSequentialGroup()
                                        .addComponent(btndangnhap)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                        .addComponent(btnthoat))
                                    .addComponent(txttaikkhoanlogin)
                                    .addComponent(txtpasslogin)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnloginLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(lblquenmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnloginLayout.setVerticalGroup(
            pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnloginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txttaikkhoanlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpasslogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(lblquenmatkhau)
                .addGap(18, 18, 18)
                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndangnhap)
                    .addComponent(btnthoat))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pncard.add(pnlogin, "card2");

        pnquenmk.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Tài Khoản");

        txttaikhoanquenmk.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lbldangnhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldangnhap.setText("Quay Lại Đăng Nhập");
        lbldangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbldangnhapMousePressed(evt);
            }
        });

        btnguimaxacnhan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnguimaxacnhan.setText("Gửi Mã Xác Nhận");
        btnguimaxacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguimaxacnhanActionPerformed(evt);
            }
        });

        btnthoatquenmk.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnthoatquenmk.setText("Thoát");
        btnthoatquenmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatquenmkActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Quên Mật Khẩu");

        javax.swing.GroupLayout pnquenmkLayout = new javax.swing.GroupLayout(pnquenmk);
        pnquenmk.setLayout(pnquenmkLayout);
        pnquenmkLayout.setHorizontalGroup(
            pnquenmkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnquenmkLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbldangnhap)
                .addGap(196, 196, 196))
            .addGroup(pnquenmkLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(pnquenmkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(pnquenmkLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addGroup(pnquenmkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnquenmkLayout.createSequentialGroup()
                                .addComponent(btnguimaxacnhan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnthoatquenmk))
                            .addComponent(txttaikhoanquenmk, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        pnquenmkLayout.setVerticalGroup(
            pnquenmkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnquenmkLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addGroup(pnquenmkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttaikhoanquenmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(lbldangnhap)
                .addGap(40, 40, 40)
                .addGroup(pnquenmkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguimaxacnhan)
                    .addComponent(btnthoatquenmk))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pncard.add(pnquenmk, "card3");

        pnmaxacnhan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Tài Khoản");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Mã Xác Nhận");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Mật Khẩu Mới");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Xác Nhận Mật Khẩu");

        btndoimatkhau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btndoimatkhau.setText("Đổi Mật Khẩu");

        btnguilaima.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnguilaima.setText("Gửi Lại Mã");
        btnguilaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguilaimaActionPerformed(evt);
            }
        });

        btnthoatxacnhan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnthoatxacnhan.setText("Thoát");

        lblgmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtmaxacnhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtmatkhaumoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtxacnhanmatkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnmaxacnhanLayout = new javax.swing.GroupLayout(pnmaxacnhan);
        pnmaxacnhan.setLayout(pnmaxacnhanLayout);
        pnmaxacnhanLayout.setHorizontalGroup(
            pnmaxacnhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnmaxacnhanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnmaxacnhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnmaxacnhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnmaxacnhanLayout.createSequentialGroup()
                        .addComponent(btndoimatkhau)
                        .addGap(18, 18, 18)
                        .addComponent(btnguilaima)
                        .addGap(18, 18, 18)
                        .addComponent(btnthoatxacnhan))
                    .addGroup(pnmaxacnhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtmaxacnhan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtxacnhanmatkhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                        .addComponent(txtmatkhaumoi, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblgmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnmaxacnhanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltimeout, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        pnmaxacnhanLayout.setVerticalGroup(
            pnmaxacnhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnmaxacnhanLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnmaxacnhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblgmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnmaxacnhanLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(47, 47, 47)
                        .addGroup(pnmaxacnhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtmaxacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(pnmaxacnhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtmatkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(pnmaxacnhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtxacnhanmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(pnmaxacnhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndoimatkhau)
                    .addComponent(btnguilaima)
                    .addComponent(btnthoatxacnhan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltimeout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pncard.add(pnmaxacnhan, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pncard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pncard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangnhapActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btndangnhapActionPerformed

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btnguimaxacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguimaxacnhanActionPerformed
        // TODO add your handling code here:
        if (txttaikhoanquenmk.getText().equals("")) {
            MessageConfig.messageText("không đươc để trống tài khoản", rootPane);
            return;
        }
        if (!RegexPattern.checkgmail(txttaikhoanquenmk.getText())) {
            MessageConfig.messageText("tài khoản không đúng định dạng", rootPane);
            return;
        }
        if (accountServic.selectFindOneServic(txttaikhoanquenmk.getText()) == null) {
            MessageConfig.messageText("tài khoản không có trong hệ thống", rootPane);
            return;
        }
        accountServic.guimaxacnhan(txttaikhoanquenmk.getText());
        lblgmail.setText(txttaikhoanquenmk.getText());
        showlayout("card4");
    }//GEN-LAST:event_btnguimaxacnhanActionPerformed

    private void btnthoatquenmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatquenmkActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnthoatquenmkActionPerformed

    private void lblquenmatkhauMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblquenmatkhauMousePressed
        // TODO add your handling code here:
        showlayout("card3");
    }//GEN-LAST:event_lblquenmatkhauMousePressed

    private void lbldangnhapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangnhapMousePressed
        // TODO add your handling code here:
        showlayout("card2");
    }//GEN-LAST:event_lbldangnhapMousePressed

    private void btnguilaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguilaimaActionPerformed
        // TODO add your handling code here:
        accountServic.guimaxacnhan(lblgmail.getText());
        accountServic.stopTimeOut();
        accountServic.TimeOut(lbltimeout);
    }//GEN-LAST:event_btnguilaimaActionPerformed

    void showlayout(String cardselect) {
        card.show(pncard, cardselect);
    }

    public void actiontimeOut() {
        accountServic.TimeOut(lbltimeout);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormLogin dialog = new FormLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangnhap;
    private javax.swing.JButton btndoimatkhau;
    private javax.swing.JButton btnguilaima;
    private javax.swing.JButton btnguimaxacnhan;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btnthoatquenmk;
    private javax.swing.JButton btnthoatxacnhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbldangnhap;
    private javax.swing.JLabel lblgmail;
    private javax.swing.JLabel lblquenmatkhau;
    private javax.swing.JLabel lbltimeout;
    private javax.swing.JPanel pncard;
    private javax.swing.JPanel pnlogin;
    private javax.swing.JPanel pnmaxacnhan;
    private javax.swing.JPanel pnquenmk;
    private javax.swing.JPasswordField txtmatkhaumoi;
    private javax.swing.JTextField txtmaxacnhan;
    private javax.swing.JPasswordField txtpasslogin;
    private javax.swing.JTextField txttaikhoanquenmk;
    private javax.swing.JTextField txttaikkhoanlogin;
    private javax.swing.JPasswordField txtxacnhanmatkhau;
    // End of variables declaration//GEN-END:variables
}
