/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_server;

import DAO.monhocDAO;
import help.JDBCHelp;
import help.readFile;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.cauhoiModel;
import model.dapanModel;
import model.dethiModel;
import model.doanvan_tienganhModel;
import model.monhocModel;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import servic.cauhoiservic;
import servic.daonvanservic;
import servic.dapanservic;
import servic.dethiservic;

/**
 *
 * @author Admin
 */
public class Form extends javax.swing.JFrame {

    private dethiservic dethiservic;
    private cauhoiservic cauhoiservic;
    private dapanservic dapanservic;
    private monhocDAO monhocdao;
    private String monhoc;
    private dethiModel dethi;
    private List<cauhoiModel> listcauhoi;
    private List<doanvan_tienganhModel> listdoanvan;
    private daonvanservic doanvanservic;

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        try {
            JDBCHelp.con = JDBCHelp.getconnect();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        dethiservic = new dethiservic();
        cauhoiservic = new cauhoiservic();
        dapanservic = new dapanservic();

        monhocdao = new monhocDAO();
        listcauhoi = new ArrayList<>();
        listdoanvan = new ArrayList<>();
        doanvanservic = new daonvanservic();
        loadcombo();
        monhoc = ((monhocModel) cbomonhoc.getSelectedItem()).getMaMonHoc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fchooser = new javax.swing.JFileChooser();
        btnthem = new javax.swing.JButton();
        btnchonfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblfilename = new javax.swing.JLabel();
        txtmadethi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbomonhoc = new javax.swing.JComboBox<>();
        tamotangan = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnchonfile.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnchonfile.setText("Chọn File");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("File Name");

        lblfilename.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel2.setText("Mã Đề Thi");

        jLabel3.setText("Môn Học");

        cbomonhoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbomonhocItemStateChanged(evt);
            }
        });

        ta.setColumns(20);
        ta.setRows(5);
        ta.setBorder(javax.swing.BorderFactory.createTitledBorder("Mô Tả Ngắn"));
        tamotangan.setViewportView(ta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblfilename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(btnthem))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtmadethi, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnchonfile, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbomonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(tamotangan, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmadethi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnchonfile, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbomonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(tamotangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblfilename, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnthem)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:
            JDBCHelp.con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (checkMaDeThi()) {
            setdethi();
            insert();
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void cbomonhocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbomonhocItemStateChanged
        // TODO add your handling code here:
        monhoc = ((monhocModel) cbomonhoc.getSelectedItem()).getMaMonHoc();
    }//GEN-LAST:event_cbomonhocItemStateChanged

    public void setdethi() {
        dethi = new dethiModel();
        dethi.setMadethi(txtmadethi.getText());
        dethi.setMamonhoc(monhoc);
        dethi.setNgaytao(new Timestamp(new java.util.Date().getTime()));
        dethi.setNguoitao("damvuong0987@gmail.com");
        dethi.setMotangan(ta.getText());
    }

    public void insert() {
        Document doc = getdocument();
        if (doc != null) {
            dethiservic.settendethi(dethi, doc);
            Integer stt = 1;
            if (doc.select(".question-item-main-panel").size() < 40) {
                Elements els = doc.select(".question-item-main-panel");
                int i = 1;
                for (Element el : els) {
                    doanvanservic.setdoanvanservic(listdoanvan, el, dethi.getMadethi(), i);
                    stt = cauhoiservic.setcauhoiservicmonTiengAnh(listcauhoi, el, dethi.getMadethi(), dapanservic, stt, dethi.getMadethi() + "_DV" + i);
                    i++;
                }
            } else {
                Elements els = doc.select(".question-item-main-panel");
                cauhoiservic.setcauhoiservic(listcauhoi, els, dethi.getMadethi(), dapanservic);
            }
            dethiservic.insert(dethi);
            if (!listdoanvan.isEmpty() || listdoanvan != null) {
                for (doanvan_tienganhModel dvModel : listdoanvan) {
                    doanvanservic.insert(dvModel);
                }
            }
            for (cauhoiModel cauhoi : listcauhoi) {
                cauhoiservic.insert(cauhoi);
                for (dapanModel dapan : cauhoi.getDapanlist()) {
                    dapanservic.insert(dapan);
                }
            }
            if (!listdoanvan.isEmpty() || listdoanvan != null) {
                listdoanvan.removeAll(listdoanvan);
            }
            listcauhoi.removeAll(listcauhoi);
            JOptionPane.showMessageDialog(rootPane, "success");
        }
    }

    public boolean checkMaDeThiFromDataBase() {
        if (dethiservic.checkmadethi(txtmadethi.getText())) {
            return true;
        }
        JOptionPane.showMessageDialog(this, "mã đề thi đã tồn tại");
        return false;
    }

    public boolean checkMaDeThi() {
        String a = txtmadethi.getText();
        if (txtmadethi.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "không được để trống mã đề thi");
            return false;
        }
        return checkMaDeThiFromDataBase();
    }

    public void loadcombo() {
        List<monhocModel> list = monhocdao.select();
        cbomonhoc.removeAllItems();
        for (monhocModel monhoc : list) {
            cbomonhoc.addItem(monhoc);
        }
    }

    public Document getdocument() {
        return Jsoup.parse(readFile.readFiletoString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchonfile;
    private javax.swing.JButton btnthem;
    private javax.swing.JComboBox<monhocModel> cbomonhoc;
    private javax.swing.JFileChooser fchooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblfilename;
    private javax.swing.JTextArea ta;
    private javax.swing.JScrollPane tamotangan;
    private javax.swing.JTextField txtmadethi;
    // End of variables declaration//GEN-END:variables
}
