/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_server;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Admin
 */
public class loginParent extends javax.swing.JDialog {

    /**
     * Creates new form login
     */
    public loginParent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
    void init(){
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupGioiTInh = new javax.swing.ButtonGroup();
        pnparent = new javax.swing.JPanel();
        pnmisspass = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        lblmisspasslogin = new javax.swing.JLabel();
        lblsignupfrommisspass = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        pnsignup = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        rbtnnam = new javax.swing.JRadioButton();
        rbtnnu = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        lblsignin = new javax.swing.JLabel();
        lblmissasssignup = new javax.swing.JLabel();
        pnlogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        lblsignup = new javax.swing.JLabel();
        lblmisspass = new javax.swing.JLabel();
        pnmaxacthuc = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPasswordField5 = new javax.swing.JPasswordField();

        btngroupGioiTInh.add(rbtnnam);
        btngroupGioiTInh.add(rbtnnu);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnparent.setMaximumSize(new java.awt.Dimension(600, 450));
        pnparent.setPreferredSize(new java.awt.Dimension(600, 450));
        pnparent.setLayout(new java.awt.CardLayout());

        pnmisspass.setBackground(new java.awt.Color(255, 255, 255));
        pnmisspass.setMaximumSize(new java.awt.Dimension(600, 450));
        pnmisspass.setPreferredSize(new java.awt.Dimension(600, 450));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Quên Mật Khẩu");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Bạn Sẽ Nhận Được Mã Xác Thự Tại Tài Khoản Gmail Của Mình");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Gmail");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lblmisspasslogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblmisspasslogin.setText("Đăng Nhập Ngay ?");
        lblmisspasslogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmisspassloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblmisspassloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblmisspassloginMouseExited(evt);
            }
        });

        lblsignupfrommisspass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblsignupfrommisspass.setText("Bạn Chưa Có Tài Khoản ?");
        lblsignupfrommisspass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsignupfrommisspassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsignupfrommisspassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsignupfrommisspassMouseExited(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton5.setText("Gửi Mật Khẩu");

        javax.swing.GroupLayout pnmisspassLayout = new javax.swing.GroupLayout(pnmisspass);
        pnmisspass.setLayout(pnmisspassLayout);
        pnmisspassLayout.setHorizontalGroup(
            pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnmisspassLayout.createSequentialGroup()
                .addGroup(pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnmisspassLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnmisspassLayout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))
                            .addGroup(pnmisspassLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel10))))
                    .addGroup(pnmisspassLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnmisspassLayout.createSequentialGroup()
                                .addComponent(lblmisspasslogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblsignupfrommisspass))
                            .addComponent(jLabel11))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        pnmisspassLayout.setVerticalGroup(
            pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnmisspassLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10)
                .addGap(91, 91, 91)
                .addGroup(pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(54, 54, 54)
                .addComponent(jLabel11)
                .addGap(60, 60, 60)
                .addGroup(pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmisspasslogin)
                    .addComponent(lblsignupfrommisspass))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pnparent.add(pnmisspass, "card4");

        pnsignup.setBackground(new java.awt.Color(255, 255, 255));
        pnsignup.setMaximumSize(new java.awt.Dimension(600, 450));
        pnsignup.setPreferredSize(new java.awt.Dimension(600, 350));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Đăng Ký");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Gmail");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Mật Khẩu");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Xác Nhận Mật Khẩu");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Tên");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Giới Tính");

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setText("Đăng Ký");

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton4.setText("Thoát");

        rbtnnam.setBackground(new java.awt.Color(255, 255, 255));
        rbtnnam.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        rbtnnam.setText("Nam");

        rbtnnu.setBackground(new java.awt.Color(255, 255, 255));
        rbtnnu.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        rbtnnu.setText("Nữ");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jPasswordField3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lblsignin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblsignin.setText("Đăng Nhập Ngay ?");
        lblsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsigninMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsigninMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsigninMouseExited(evt);
            }
        });

        lblmissasssignup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblmissasssignup.setText("Quên Mật Khẩu ?");
        lblmissasssignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmissasssignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblmissasssignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblmissasssignupMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnsignupLayout = new javax.swing.GroupLayout(pnsignup);
        pnsignup.setLayout(pnsignupLayout);
        pnsignupLayout.setHorizontalGroup(
            pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnsignupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(239, 239, 239))
            .addGroup(pnsignupLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnsignupLayout.createSequentialGroup()
                            .addComponent(jButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnsignupLayout.createSequentialGroup()
                            .addComponent(rbtnnam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnnu))
                        .addComponent(jPasswordField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnsignupLayout.createSequentialGroup()
                        .addComponent(lblsignin)
                        .addGap(64, 64, 64)
                        .addComponent(lblmissasssignup)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnsignupLayout.setVerticalGroup(
            pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnsignupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rbtnnam)
                    .addComponent(rbtnnu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsignin)
                    .addComponent(lblmissasssignup))
                .addGap(16, 16, 16))
        );

        pnparent.add(pnsignup, "card3");

        pnlogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlogin.setForeground(new java.awt.Color(153, 153, 153));
        pnlogin.setMaximumSize(new java.awt.Dimension(600, 450));
        pnlogin.setPreferredSize(new java.awt.Dimension(600, 350));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Gmail");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Mật Khẩu");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton2.setText("Đăng Nhập");

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Đăng Nhập");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lblsignup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblsignup.setText("Bạn Chưa Có Tài Khoản ?");
        lblsignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsignupMouseExited(evt);
            }
        });

        lblmisspass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblmisspass.setText("Quên Mật Khẩu ?");
        lblmisspass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmisspassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblmisspassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblmisspassMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnloginLayout = new javax.swing.GroupLayout(pnlogin);
        pnlogin.setLayout(pnloginLayout);
        pnloginLayout.setHorizontalGroup(
            pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnloginLayout.createSequentialGroup()
                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnloginLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(pnloginLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(48, 48, 48)
                        .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblsignup)
                                .addComponent(lblmisspass, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnloginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(197, 197, 197))
        );
        pnloginLayout.setVerticalGroup(
            pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnloginLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(46, 46, 46)
                .addComponent(lblsignup)
                .addGap(40, 40, 40)
                .addComponent(lblmisspass)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pnparent.add(pnlogin, "card2");

        pnmaxacthuc.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Xác Thực Mã Xác Nhận");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Mã Xác Thực");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Gmail");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Mật Khẩu Mới");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Xác Nhận Mật Khẩu Mới");

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Đổi Mật Khẩu");

        javax.swing.GroupLayout pnmaxacthucLayout = new javax.swing.GroupLayout(pnmaxacthuc);
        pnmaxacthuc.setLayout(pnmaxacthucLayout);
        pnmaxacthucLayout.setHorizontalGroup(
            pnmaxacthucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnmaxacthucLayout.createSequentialGroup()
                .addGroup(pnmaxacthucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnmaxacthucLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnmaxacthucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(39, 39, 39)
                        .addGroup(pnmaxacthucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnmaxacthucLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jButton6))
                    .addGroup(pnmaxacthucLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel13)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        pnmaxacthucLayout.setVerticalGroup(
            pnmaxacthucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnmaxacthucLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel13)
                .addGap(32, 32, 32)
                .addGroup(pnmaxacthucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(pnmaxacthucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnmaxacthucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnmaxacthucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(32, 32, 32))
        );

        pnparent.add(pnmaxacthuc, "card5");

        getContentPane().add(pnparent, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblsignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsignupMouseClicked
        // TODO add your handling code here:
        showlayout("card3");
    }//GEN-LAST:event_lblsignupMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblsignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsignupMouseEntered
        // TODO add your handling code here:
        setcolorlblmouseHover(lblsignup);
    }//GEN-LAST:event_lblsignupMouseEntered

    private void lblsignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsignupMouseExited
        // TODO add your handling code here:
        setcolorlblmouseOut(lblsignup);
    }//GEN-LAST:event_lblsignupMouseExited

    private void lblmisspassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmisspassMouseEntered
        // TODO add your handling code here:
        setcolorlblmouseHover(lblmisspass);
    }//GEN-LAST:event_lblmisspassMouseEntered

    private void lblmisspassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmisspassMouseExited
        // TODO add your handling code here:
        setcolorlblmouseOut(lblmisspass);
    }//GEN-LAST:event_lblmisspassMouseExited

    private void lblsigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsigninMouseEntered
        // TODO add your handling code here:
        setcolorlblmouseHover(lblsignin);
    }//GEN-LAST:event_lblsigninMouseEntered

    private void lblsigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsigninMouseExited
        // TODO add your handling code here:
        setcolorlblmouseOut(lblsignin);
    }//GEN-LAST:event_lblsigninMouseExited

    private void lblmissasssignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmissasssignupMouseEntered
        // TODO add your handling code here:
        setcolorlblmouseHover(lblmissasssignup);
    }//GEN-LAST:event_lblmissasssignupMouseEntered

    private void lblmissasssignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmissasssignupMouseExited
        // TODO add your handling code here:
        setcolorlblmouseOut(lblmissasssignup);
    }//GEN-LAST:event_lblmissasssignupMouseExited

    private void lblsigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsigninMouseClicked
        // TODO add your handling code here:
        showlayout("card2");
    }//GEN-LAST:event_lblsigninMouseClicked

    private void lblmissasssignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmissasssignupMouseClicked
        // TODO add your handling code here:
        showlayout("card4");
    }//GEN-LAST:event_lblmissasssignupMouseClicked

    private void lblmisspassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmisspassMouseClicked
        // TODO add your handling code here:
        showlayout("card4");
    }//GEN-LAST:event_lblmisspassMouseClicked

    private void lblmisspassloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmisspassloginMouseEntered
        // TODO add your handling code here:
        setcolorlblmouseHover(lblmisspasslogin);
    }//GEN-LAST:event_lblmisspassloginMouseEntered

    private void lblmisspassloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmisspassloginMouseExited
        // TODO add your handling code here:
        setcolorlblmouseOut(lblmisspasslogin);
    }//GEN-LAST:event_lblmisspassloginMouseExited

    private void lblmisspassloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmisspassloginMouseClicked
        // TODO add your handling code here:
        showlayout("card2");
    }//GEN-LAST:event_lblmisspassloginMouseClicked

    private void lblsignupfrommisspassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsignupfrommisspassMouseClicked
        // TODO add your handling code here:
        showlayout("card3");
    }//GEN-LAST:event_lblsignupfrommisspassMouseClicked

    private void lblsignupfrommisspassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsignupfrommisspassMouseEntered
        // TODO add your handling code here:
        setcolorlblmouseHover(lblsignupfrommisspass);
    }//GEN-LAST:event_lblsignupfrommisspassMouseEntered

    private void lblsignupfrommisspassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsignupfrommisspassMouseExited
        // TODO add your handling code here:
        setcolorlblmouseOut(lblsignupfrommisspass);
    }//GEN-LAST:event_lblsignupfrommisspassMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        showlayout("card2");
    }//GEN-LAST:event_formWindowOpened
    
    void showlayout(String cardName){
    CardLayout card = (CardLayout) pnparent.getLayout();
        card.show(pnparent, cardName);
    }
    
    void setcolorlblmouseHover(JLabel lbl){
    lbl.setForeground(Color.gray);
    }
    void setcolorlblmouseOut(JLabel lbl){
    lbl.setForeground(Color.black);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                loginParent dialog = new loginParent(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngroupGioiTInh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblmissasssignup;
    private javax.swing.JLabel lblmisspass;
    private javax.swing.JLabel lblmisspasslogin;
    private javax.swing.JLabel lblsignin;
    private javax.swing.JLabel lblsignup;
    private javax.swing.JLabel lblsignupfrommisspass;
    private javax.swing.JPanel pnlogin;
    private javax.swing.JPanel pnmaxacthuc;
    private javax.swing.JPanel pnmisspass;
    private javax.swing.JPanel pnparent;
    private javax.swing.JPanel pnsignup;
    private javax.swing.JRadioButton rbtnnam;
    private javax.swing.JRadioButton rbtnnu;
    // End of variables declaration//GEN-END:variables
}
